[tool.poetry]
name = "biteki-hantei"
version = "0.1.0"
description = ""
authors = ["tomo3141592653 <tomo3141592653@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
torch = "^2.4.0"
torchvision = "^0.19.0"
numpy = "^2.0.1"
pillow = "^10.4.0"
clip = {git = "https://github.com/openai/CLIP.git"}
tqdm = "^4.66.4"
packaging = "^24.1"
rawpy = "^0.22.0"
gradio = "^4.39.0"
pillow-heif = "^0.18.0"
scikit-learn = "^1.5.1"
pyinstaller = "^6.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
